version: '3.1'

services:
  nginx_svc:
    image: nginx
    container_name: dns-hijacking-nginx
    # restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./nginx/wwwroot:/usr/share/nginx/wwwroot
    #links:
    # - dnsmasq_svc:dnsmasq

  dnsmasq_svc:
    image: jpillora/dnsmasq
    container_name: dns-hijacking-dnsmasq
    # restar: always
    environment:
      - TZ=Asia/Shanghai
      - HTTP_USER=Kiki
      - HTTP_PASS=Kiki
    ports:
      - 53:53/udp
      - 8080:8080
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    links:
      - nginx_svc:nginx


